#include <pebble.h>
#pragma once
bool is_morning_prep_time();
bool is_afternoon_prep_time();
bool is_reading_time();
bool is_work_time();
bool is_travel_time();
bool is_gym_time();
bool is_meditation_time();
bool is_water_time();